### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by PieterGit** [xdrip-js/Lookout#69]
With a fresh `dev` checkout I get:
```
# DEBUG=trasnmitterIO:*,smp,transmitter,bluetooth-manager Lookout
(node:2188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'date' of undefined
    at validateTxmitterCalibration (/root/src/Lookout/calibration.js:629:38)
    at Object.validateCalibration (/root/src/Lookout/calibration.js:687:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:2188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'date' of undefined
    at validateTxmitterCalibration (/root/src/Lookout/calibration.js:629:38)
    at Object.validateCalibration (/root/src/Lookout/calibration.js:687:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:2188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

Anybody know how that needs to be fixed?

**Comment by jpcunningh** [comment]
I'll have a fix in dev momentarily.
